### ISSUE TITLE
Strange lines which prevents normal reading

### ISSUE THREAD

**Issue by Sudokamikaze** [CommitteeOfZero/zero-patch#1]
Hi guys, I'm having some troubles with your patchset

I've installed it by your instructions and here's [screenshots ](https://imgur.com/a/fCSw3As)of the game

Also I've tried to disable/enable options in configuration but no way, nothing changes at all.

Any suggestions or ideas which option(s) caused it?

**Comment by drdaxxy** [comment]
Sorry to hear that.

- What operating system, GPU, and GPU driver version are you using?
- Does the problem also occur with the unpatched version of the game? (Close the game, rename `dinput8.dll` in the game folder to something else, start the game again)

**Comment by Sudokamikaze** [comment]
@drdaxxy 
 Fresh install of Windows 8.1 x64 bit
My GPU is Radeon HD 7570m and latest driver from official [site](https://support.amd.com/en-us/kb-articles/Pages/AMD-Radeon-7000-Series-Drivers.aspx)

Same situation with renamed `dinput8.dll`, probably something wrong on my side. Sorry for the false call
