### ISSUE TITLE
Linux: update instructions to include installation of VC runtime 2017

### ISSUE THREAD

**Issue by mathdu07** [CommitteeOfZero/zero-patch#2]
I followed the instructions to install the Steins;gate 0 (steam) patch on Linux, with Proton.
Unfortunately, when executing the installer with proton, it silently crashed.
To fix it, I installed Microsoft Visual C++ runtime 2017 inside the game's prefix with protontricks, via this command in a shell :
```
protontricks 825630 vcrun2017
```

I think that it would be a good idea to state in the linux instructions that vcrun2017 is needed, since it is not intially installed by Proton.

**Comment by rainx0r** [comment]
Great point. Arguably the linux installation instructions of the S;G0 Steam patch could have used a bit more testing...

Besides installing vcrun2017, was there anything else you had to do that deviates from the instructions? Was the rest of the procedure correctly outlined and the commands precise? If not please advise so we can update accordingly alongside adding the instruction to install vcrun2017.

**Comment by mathdu07** [comment]
No, besides installing vcrun2017 I just followed the procedure. The rest of the procedure seems clear enough to me.
Btw I haven't encountered any issues so far while playing S;G0 with the patch, great job :-)
